name: dart_opencv_sdk
description: This package supports OpenCV sdk for dart language, slowly developing
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  image: ^4.0.17
  #   path: ^1.8.0
